### ISSUE TITLE
インストール手順道理にしてもインストールできない

### ISSUE THREAD

**Issue by kumi0708** [bexide/BxUni-3dNoiseTextureGenerator#1]
インストール手順道理にしてもインストールできない

他のGitHubにオープンソースのプロジェクトと同じインストール方法だとおものだけど
BxUni-3dNoiseTextureGeneratorの項目出ていない気がする。

![image](https://user-images.githubusercontent.com/8042757/212482432-0ccab5a9-1d7d-4730-9fdb-dde793a94175.png)

**Comment by hayashi-bxj** [comment]
報告ありがとうございます。
ご指摘の通りパッケージの登録が漏れておりました。
改めて登録しましたので現在は一覧に出るかと思います。
お試しください。

**Comment by kumi0708** [comment]
再設定して、パッケージが読みこまれました。
closeします。
![image](https://user-images.githubusercontent.com/8042757/212803651-94de8764-28bd-4615-82a0-91f8e29dcc4a.png)

**Comment by kumi0708** [comment]
再設定して、パッケージが読みこまれました。
closeします。
![image](https://user-images.githubusercontent.com/8042757/212803810-b2ef1f47-1b93-4a72-bc67-9cb007a7a592.png)
